equinixmetal-helm/krakend

templates/cm-config.yaml, values.yaml
As done in the examples in the documentation, we originally had an
opinionated template for the endpoints which would only allow for
setting one endpoint to one backend. While this was nice for testing,
this is not ideal if we want to allow folks to have more control over
their endpoints.
So, we now are switching to allowing a raw endpoint configuration
insertion via Krakend's flexible configuration partials [1]. While
service authors will need be more acquainted with lura configuration,
specifically the endpoint constructs [2], it allows us to iterate faster
on verifying the krakend gateway and getting that deployed.
[1] https://www.krakend.io/docs/configuration/flexible-config/
[2] https://www.krakend.io/docs/endpoints/
Signed-off-by: Juan Antonio Osorio …
=> Use direct endpoint entries in default configuration

templates/cm-config.yaml
The [Portón](https://github.com/infratographer/porton) project injects
plugins through a specific path (`/usr/lib/krakend/plugins/`) by
default. This takes that assumption into use by default and enables the
needed configuration.
Note that this will stay this way while we get this working. In the
future, we might make this optional if others want to take this helm
chart into use.
=> Add configuration for injecting plugins by default

templates/deployment.yaml
This uses krakend's default health check [1] to set up a k8s
`livenessProbe`. It's currently using default values which we might
adjust as needed once we run and analyze the gateway in an environment.
[1] https://www.krakend.io/docs/service-settings/health/
=> Add initial setting for liveness probe

templates/cm-partials.yaml, templates/deployment.yaml, values.yaml
Krakend.io endpoints may take most of the configuration and can get
quite big. Big enough that the ConfigMap's 1.5Mb of storage is not
enough. To address this limitation, we now allow for users to specify if
they want to import endpoints from a container image. This can be
enabled via the `krakend.endpoints.fromImage` value. However, since we
don't know what image they'll use, they need to specify this too.
So, a minimal values file that enables this configuration would look as
follows:
```yaml
krakend:
krakend:
endpoints:
fromImage: true
image:
registry: "foo"
repository: "bar"
tag: "baz"
```
The idea is that folks will be able to generate images that will be
copied into the main API Gateway container's partials configuration.
Note that it's also possible to override the command to run …
=> Enable importing endpoint configuration from a container image

README.md, values.yaml
We were initially assuming that this would be very targetted towards
Portón; however, so far it all seems general enough that we could
develop and promote a more general purpose helm chart.
=> Switch default image to use krakend upstream

.github/workflows/test.yaml, README.md, README.md.gotmpl, templates/_helpers.tpl, templates/deployment.yaml, tests/with-extra-mounts/values.yaml, values.yaml
In cases where folks want to deploy krakend enterprise, they'd need to
have the LICENSE file in a specific location. With the current
configuratoin it's not trivial... So, this changes the configuration
mount to instead exist in a sub-directory as opposed to using
`/etc/krakend` directly.
On the other hand, this also added the generic keys `extraVolumeMounts`
and `extraVolumes` which allow us to inject the needed license file. An
example of using this would look as follows:
```yaml
extraVolumeMounts:
- name: license
mountPath: /etc/krakend/LICENSE
readOnly: true
extraVolumes:
- name: license
secret:
secretName: krakend-license
```
This also now changes the base directory for the krakend configs to be `/etc/krakend-src`, since that allows us to not have conflicting bind-mounts with the …
=> Add ability to insert extra volumes (useful for setting up license)

README.md, templates/service.yaml, values.yaml
This is useful when using utilities like MetalLB that work via
annotations.
=> Add ability to set up custom service annotations

.github/workflows/release.yaml
This will create a nice little relesae in GitHub with automatic release
notes.
TODO: Ensure the release points to the generated tarball.
=> Automatically create a GitHub release when a tag is detected

Makefile
We were modifying the README directly while we could have just called
`helm-docs`. This simplifies and solves some bugs in the docs
generation for releases.
=> Simplify Release version updates

.github/workflows/test.yaml, templates/service.yaml, tests/with-templated-annotations/values.yaml
This is useful for cluster-specific settings that require extra logic.
=> Allow for using templated service annotations

README.md, templates/deployment.yaml, values.yaml
This adds secure defaults for the containers' securityContext
configuration.
Note that the user `1000` was chosen because it's the default that the krakend upstream container provisions.
=> Add secure defaults

templates/deployment.yaml
This uses the health endpoint for the readiness probe.
=> Use health endpoint for readiness probe

README.md, values.yaml
This makes sure that access to the health endpoint doesn't show up in the logs by default. Folks can still modify this by having a custom service configuration set up.
=> Skip health endpoint from access logs in default configuration

README.md, templates/deployment.yaml, values.yaml
Argo Rollouts is a project that allows us to replace Kubernetes
Deployments and handle more complex deployment strategies [1]. It
currently supports canary and blue green deployments, with the added
value of providing a way of doing analysis on how a rollout is going
based on metrics (e.g. prometheus).
Testing this out, it seems like quite an ideal way of managing the
krakend API Gateway as it would greatly reduce the risk of rolling out
changes if we set up the rollout strategy and analysis templates
appropriately.
Testing this out locally, it seems like quite a versatile tool. However,
I wanted to get some more feedback first.
One caveat I see is that the Kuberentes CRD's are v1alpha1, which is not
ideal.
[1] https://argo-rollouts.readthedocs.io/en/stable/
Signed-off-by: Juan Antonio …
=> Add support for Argo Rollouts as a deployment

.github/workflows/test.yaml, Chart.yaml, README.md, templates/deployment.yaml, values.schema.json
This ensures that we get extra validation of the values when installing
the chart and gives us better CI coverage.
This also addresses a warning generated by helm lint.
Thanks @andy-v-h for suggesting this!
=> Add relevant JSON schema and lint job

Makefile
This helps us have the release tags in commited branches and thus makes
our auto-release generation actually output relevant release notes. With
the previous workflow, we'd have the tag in a commit HEAD outside of
`main`'s tree.
=> release: Tag before doing the release commit

README.md, templates/deployment.yaml, values.schema.json, values.yaml
Both Argo Rollouts and kube Deployments have the `strategy` key, so
let's use that instead as opposed to relying solely on the argo rollouts
key.
=> Replace `rolloutStrategy` with `strategy`

README.md, templates/deployment.yaml, templates/service-monitor.yaml, values.yaml
This adds an optional serviceMonitor to the `krakend` deployment.  Note: `krakend` will need to expose prometheus in the config as well - something like:
```json
"telemetry/opencensus": {
"sample_rate": 100,
"reporting_period": 1,
"enabled_layers": {
"backend": true,
"router": true
},
"exporters": {
"prometheus": {
"port": 9091,
"tag_host": true,
"tag_path": true,
"tag_method": true,
"tag_statuscode": true
}
}
}
```
=> Add optional serviceMonitor to helm chart

templates/deployment.yaml
We only need those checksums if we're using the ConfigMap approach
that's used for testing. If we're using the all-in-one image, these
checksum annotations are not needed.
=> Don't annotate checksums if we're using the all-in-one image

Makefile
The app version should reflect the version of the supported krakend
release, this PR updates the `release` Makefile target to do so.
This now requires the `yq` command to be installed on the release
manager's machine.
=> Update Chart appVersion on release

README.md, templates/service.yaml, values.yaml
Hey folks 👋 ,
First of all, thanks a lot for your work on that repos 🎉 it is really helpful and useful🙏 
The goal of this PR is to reach the metrics port from the kubernetes service object in order to scrape it from prometheus.
I know there is the serviceMonitor object which is already present but some of us don't have an implementation of the monitoring stack with the prometheus-operator
Don't hesitate to reach for any questions 😉 
Cheers ☀️
=> feat: add extra service port to reach the metrics port

README.md, templates/poddistruptionbudget.yaml, values.yaml
Hey,
thank you for putting this chart online.
I'm probably going to use it, but needed a pdb. This PR adds the possibility to optionally configure it.
Thanks again.
=> add optional resource PodDisruptionBudget

templates/deployment.yaml
As documented:
If a HorizontalPodAutoscaler (or any similar API for horizontal scaling) is managing scaling for a Deployment, don't set .spec.replicas.
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#replicas
=> fix: hpa manages Deployment.replicas when configured

templates/deployment.yaml, values.yaml
When unset, k8s defaults are the following:
rollingUpdate:
maxSurge: 25%
maxUnavailable: 25%
Currently, the same values are set when deploymentType is "deployment".
After merging this patch, defaults will be the same, but we'll be able to override them independently of deploymentType.
=> fix(k8s): Deployment.strategy is independent of deploymentType

README.md, templates/deployment.yaml, templates/hpa.yaml, templates/keda.yaml, values.yaml
Allow to setup keda [ScaledObject](https://keda.sh/docs/2.13/concepts/scaling-deployments/#scaledobject-spec)
Disabled by default.
=> feat: allow to configure autoscaling with keda ScaledObject

README.md, templates/deployment.yaml, values.yaml
This pull request introduces changes to the Helm template to implement conditional logic for `deploymentAnnotations`. The update ensures that the `annotations:` block is only included in the Kubernetes Deployment manifest if `deploymentAnnotations` are defined in the `values.yaml` file.
The motivation behind this change is to keep the Deployment manifest clean and free from empty or unnecessary annotations when no `deploymentAnnotations` are specified, thereby preventing potential deployment issues and maintaining clarity in the manifest files.
- An `if` statement checks for the presence of `deploymentAnnotations` in the `values.yaml`.
- If `deploymentAnnotations` exist, the annotations block is added to the Deployment manifest.
- If there are no `deploymentAnnotations`, the annotations …
=> Add Conditional Logic for deploymentAnnotations in Helm Chart

templates/poddistruptionbudget.yaml
Inspired by what's done in [ingress-nginx chart](https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/controller-poddisruptionbudget.yaml).
=> fix: do not set pdb when Deployment/hpa/keda replicas are too low
